name: migration tests
on: 
  - pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: 
        - "mysql:5.7"
        - "mysql:8.0"
    steps:
    - uses: actions/checkout@v2

    - name: Start MySQL in Docker
      uses: addnab/docker-run-action@v3
      with:
        image: ${{ matrix.image }}
        options: "-d -p 3306:3306 -e MYSQL_ALLOW_EMPTY_PASSWORD=true -v ${{ github.workspace }}/resources/localtests-init.sql:/docker-entrypoint-initdb.d/init.sql"
        run: |
          --log-slave-updates
          --log-bin
          --binlog-format=ROW
          --gtid_mode=ON
          --enforce-gtid-consistency=ON

    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.17

    - name: migration tests
      run: "localtests/test.sh -b bin/gh-ost"
