name: migration tests
on: 
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: 
        - "mysql:5.7"
        - "mysql:8.0"
        - "percona:5.7"
        - "percona:8.0"

    steps:

    - name: "Pull ${{ matrix.image}} image"
      run: "docker pull ${{ matrix.image }}"

    - uses: actions/checkout@v2

    - name: "Start ${{ matrix.image }} primary/replica in docker-compose"
      env:
        MYSQL_SERVER_IMAGE: ${{ matrix.image }}
        MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
      run: "docker-compose -f localtests/docker-compose.yaml up -d primary replica"

    - name: "Wait for replica"
      env:
        MYSQL_SERVER_IMAGE: ${{ matrix.image }}
        MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
      run: "docker-compose -f localtests/docker-compose.yaml up wait_for_replica"

    - name: "Run localtests"
      env:
        MYSQL_SERVER_IMAGE: ${{ matrix.image }}
        MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
      run: "docker-compose -f localtests/docker-compose.yaml up --build test"
